"""initial schema

Revision ID: fca1c1626c2d
Revises: 
Create Date: 2026-06-15 16:43:47.917654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fca1c1626c2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('caption_styles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('font_family', sa.String(length=100), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('font_weight', sa.String(length=20), nullable=False),
    sa.Column('primary_color', sa.String(length=9), nullable=False),
    sa.Column('outline_color', sa.String(length=9), nullable=False),
    sa.Column('outline_width', sa.Float(), nullable=False),
    sa.Column('shadow_color', sa.String(length=11), nullable=True),
    sa.Column('shadow_offset_x', sa.Float(), nullable=False),
    sa.Column('shadow_offset_y', sa.Float(), nullable=False),
    sa.Column('highlight_color', sa.String(length=9), nullable=True),
    sa.Column('highlight_style', sa.String(length=20), nullable=False),
    sa.Column('alignment', sa.String(length=10), nullable=False),
    sa.Column('vertical_position', sa.Float(), nullable=False),
    sa.Column('max_lines', sa.Integer(), nullable=False),
    sa.Column('words_per_line', sa.Integer(), nullable=False),
    sa.Column('animation', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detected_vods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('estimated_score', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('layout_config', sqlite.JSON(), nullable=True),
    sa.Column('subtitle_style', sqlite.JSON(), nullable=True),
    sa.Column('intro_config', sqlite.JSON(), nullable=True),
    sa.Column('music_config', sqlite.JSON(), nullable=True),
    sa.Column('export_settings', sqlite.JSON(), nullable=True),
    sa.Column('segment_filters', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('training_examples', sa.Integer(), nullable=False),
    sa.Column('cv_score', sa.Float(), nullable=False),
    sa.Column('feature_importances_json', sa.Text(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('scaler_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('audio_tracks', sa.Integer(), nullable=False),
    sa.Column('proxy_path', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('project_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('caption_style', sa.JSON(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('hook_card_style', sa.JSON(), nullable=True),
    sa.Column('brand_kit', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watched_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('auto_import', sa.Boolean(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_vod_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('variant', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('video_path', sa.Text(), nullable=False),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_platform', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_url', sa.String(length=500), nullable=True),
    sa.Column('publish_error', sa.Text(), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('review_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('quality_tags', sa.JSON(), nullable=True),
    sa.Column('issue_tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('publish_decision', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('human_score', sa.Float(), nullable=True),
    sa.Column('score_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('topic_label', sa.String(length=255), nullable=True),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_segments', sa.JSON(), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('score_hook', sa.Float(), nullable=False),
    sa.Column('score_payoff', sa.Float(), nullable=False),
    sa.Column('score_humour', sa.Float(), nullable=False),
    sa.Column('score_tension', sa.Float(), nullable=False),
    sa.Column('score_clarity', sa.Float(), nullable=False),
    sa.Column('score_rhythm', sa.Float(), nullable=False),
    sa.Column('score_reasons', sa.JSON(), nullable=True),
    sa.Column('score_tags', sa.JSON(), nullable=True),
    sa.Column('cold_open_recommended', sa.Boolean(), nullable=False),
    sa.Column('cold_open_start_time', sa.Float(), nullable=True),
    sa.Column('layout_type', sa.String(length=50), nullable=True),
    sa.Column('facecam_rect', sa.JSON(), nullable=True),
    sa.Column('content_rect', sa.JSON(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('watch_time_avg', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_feedback')
    op.drop_table('segments')
    op.drop_table('clip_reviews')
    op.drop_table('clip_queue')
    op.drop_table('artifacts')
    op.drop_table('watched_channels')
    op.drop_table('templates')
    op.drop_table('projects')
    op.drop_table('ml_model_versions')
    op.drop_table('jobs')
    op.drop_table('export_profiles')
    op.drop_table('detected_vods')
    op.drop_table('caption_styles')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
